# Generated by Django 3.0.8 on 2020-07-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vedio',
            new_name='vedios',
        ),
    ]
